services:
    game:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./src:/data/game/game_example
            - ./release:/data/game/release
            - ./config.lua:/data/game/config.lua